const $=s=>document.querySelector(s),hud=$('#hud'),overlay=$('#overlay'),host=$('#panel-host'),close=$('#close-panel');
let started=false,opened=null,traveling=false,returnFocus=null;
window.visited=new Set();
let loadingValue=0;const loadingInterval=setInterval(()=>{loadingValue=Math.min(94,loadingValue+5);$('#loader .loading-bar span').style.width=loadingValue+'%';$('#loader output').textContent=loadingValue+'%'},70);
City.ready.then(async()=>{await document.fonts.ready;clearInterval(loadingInterval);$('#loader .loading-bar span').style.width='100%';$('#loader output').textContent='100%';setTimeout(()=>{const loader=$('#loader');[...loader.children].forEach(n=>n.style.visibility='hidden');const start=performance.now();function reveal(t){const f=Math.min(1,(t-start)/750),size=Math.pow(f,1.5)*Math.max(innerWidth,innerHeight)*.65+24,x1=innerWidth/2-size,y1=innerHeight/2-size,x2=innerWidth/2+size,y2=innerHeight/2+size;loader.style.clipPath=`polygon(evenodd,0 0,100% 0,100% 100%,0 100%,0 0,${x1}px ${y1}px,${x1}px ${y2}px,${x2}px ${y2}px,${x2}px ${y1}px,${x1}px ${y1}px)`;if(f<1)requestAnimationFrame(reveal);else loader.hidden=true}requestAnimationFrame(reveal)},180)});
function showPage(id,arg){opened=id;City.setMode('panel');hud.hidden=true;overlay.hidden=false;close.hidden=false;overlay.className=(id==='map'?'map-open map-overlay':id==='contact'?'contact-open':id==='projects'?'project-open':'');host.innerHTML=Pages[id](arg);overlay.scrollTop=0;close.focus({preventScroll:true});if(id==='card')wireCard();}
function closePage(){overlay.hidden=true;close.hidden=true;hud.hidden=false;opened=null;overlay.className='';City.setMode('game');City.suppressProximity(3500);returnFocus?.focus?.({preventScroll:true});}
function closeMenu(){const menu=$('#mobile-menu');menu.hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');if(!opened&&!traveling)City.setMode('game')}
function go(id,arg){if(!started||traveling)return;closeMenu();returnFocus=document.activeElement;const direct=['memo','map','hood'].includes(id);if(direct){showPage(id);return}const location=id==='card'?{...Memos[arg],id:'card'+arg}:Locations.find(l=>l.id===id);if(!location)return;traveling=true;overlay.hidden=true;close.hidden=true;opened=null;hud.hidden=false;City.travel(location.x,location.y,()=>{traveling=false;visited.add(location.id);refreshMini();showPage(id,arg)});}
$('#play').addEventListener('click',()=>{if(started)return;started=true;$('#entry').hidden=true;City.start();setTimeout(()=>{hud.hidden=false;hud.classList.add('entering')},1000)});
document.addEventListener('click',e=>{const target=e.target.closest('[data-go],[data-memo],[data-expand],[data-up],[data-hood]');if(!target)return;if(target.dataset.go!==undefined)go(target.dataset.go);else if(target.dataset.memo!==undefined)go('card',Number(target.dataset.memo));else if(target.dataset.expand!==undefined){const box=$('#job-projects-'+target.dataset.expand);box.hidden=!box.hidden;target.textContent=box.hidden?'Show projects':'Hide projects';target.setAttribute('aria-expanded',String(!box.hidden))}else if(target.hasAttribute('data-up'))overlay.scrollTo({top:0,behavior:'smooth'});else if(target.dataset.hood!==undefined){const n=Number(target.dataset.hood);$('#hood-content').innerHTML=hoodContent(n);document.querySelectorAll('[data-hood]').forEach(b=>{const selected=b===target;b.classList.toggle('selected',selected);b.setAttribute('aria-selected',String(selected))})}});
close.addEventListener('click',closePage);$('#menu-toggle').onclick=()=>{if(traveling)return;$('#mobile-menu').hidden=false;$('#menu-toggle').setAttribute('aria-expanded','true');City.setMode('menu')};$('.menu-close').onclick=closeMenu;
$('#mini-map').onclick=()=>go('map');
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};
document.querySelectorAll('.top-nav button').forEach((b,i)=>b.style.setProperty('--i',i));
function refreshMini(){const pos=City.player;$('#mini-player').style.left=pos.x/4+'%';$('#mini-player').style.top=pos.y/4+'%';$('#mini-markers').innerHTML=Locations.map(l=>`<i class="map-dot-mini" style="left:${l.x/4}%;top:${l.y/4}%;background:${visited.has(l.id)?'#fff':l.memo!==undefined?'#ff3444':'#ffab00'}"></i>`).join('')}
refreshMini();setInterval(()=>{if(started&&!hud.hidden){const p=City.player;$('#mini-player').style.left=p.x/4+'%';$('#mini-player').style.top=p.y/4+'%'}},200);
const joystick=$('#joystick'),ball=$('#joystick-ball');let joystickPointer=null;
function moveStick(e){if(joystickPointer!==e.pointerId)return;const r=joystick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.hypot(x,y),scale=len>30?30/len:1;ball.style.transform=`translate(${x*scale}px,${y*scale}px)`;City.setJoystick(Math.max(-1,Math.min(1,x/30)),Math.max(-1,Math.min(1,y/30)));e.preventDefault()}
joystick.addEventListener('pointerdown',e=>{if(traveling||opened)return;joystickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e)});joystick.addEventListener('pointermove',moveStick);function releaseStick(){joystickPointer=null;ball.style.transform='translate(0,0)';City.setJoystick(0,0)}joystick.addEventListener('pointerup',releaseStick);joystick.addEventListener('pointercancel',releaseStick);addEventListener('blur',releaseStick);
function wireCard(){const card=$('.holo-card');card.addEventListener('click',()=>card.classList.add('active'));card.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!card.classList.contains('active'))return;const b=card.getBoundingClientRect(),x=(e.clientX-b.left)/b.width,y=(e.clientY-b.top)/b.height;card.style.setProperty('--rx',(0.5-y)*18+'deg');card.style.setProperty('--ry',(x-.5)*22+'deg');card.style.setProperty('--mx',x*100+'%');card.style.setProperty('--my',y*100+'%')});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')});}
City.onProximity=id=>{if(!started||opened||traveling||!$('#mobile-menu').hidden)return;if(id.startsWith('card'))go('card',Number(id.slice(4)));else go(id)};
// Keep keyboard focus inside the active content without introducing an Escape behaviour absent from the reference contract.
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!opened)return;const focusables=[...host.querySelectorAll('a[href],button:not([disabled])'),close].filter(el=>el.getClientRects().length);if(!focusables.length)return;const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
const isSk=/\/sk\//.test(location.pathname);if(isSk){document.documentElement.lang='sk';$('#play').textContent='Hraj';$('#entry-note').textContent='Nemáte čas na skúmanie môjho portfólia?';$('#landscape p').textContent='Otočte zariadenie';document.querySelectorAll('.language').forEach(a=>{a.textContent='EN';a.href='index.html'})}else if(location.protocol!=='file:'){document.querySelectorAll('.language').forEach(a=>a.href='sk/')}
window.Reconstruction={getState:()=>({started,opened,traveling,player:City.player,camera:City.camera,visited:[...visited],mode:City.mode}),version:'A0'};
