window.Pages={about:()=>`<article class="panel about-panel"><h1>About me</h1><div class="id-card"><img class="portrait" src="assets/images/peter-oravec.webp" alt="Peter Oravec"><div class="identity"><h2>Peter Oravec</h2><p>Front-end &amp; MEAN Stack developer</p></div><a class="linkedin-icon" href="https://www.linkedin.com/in/peteroravec" aria-label="LinkedIn" target="_blank" rel="noopener">in</a></div><h2 class="story-title">Bridging the Gap Between Design and Code</h2><div class="about-copy"><p>I'm Peter, a web developer based in Bratislava, Slovakia. My work brings together design and code, with 19 years of development experience.</p><p>JavaScript and Angular are at the centre of my work. My background also covers the MEAN stack: MongoDB, Express, Angular and Node.js, connecting the browser to the services behind it.</p><p>I enjoy working on the space where visual ideas become interactive applications. A clear interface needs more than its appearance: the frontend, backend and design must work together. Experience across these disciplines helps me consider the whole product, from its first sketch to the details people use every day.</p><p>Understanding both design and development helps me translate between teams and turn shared ideas into practical, coherent software.</p></div></article>`};
const linkIcon='<span class="linkedin-icon" aria-hidden="true">in</span>';
const up='<button class="pixel-button up-button" data-up aria-label="Scroll to top">Up ↑</button>';
const paragraphs=a=>a.map(x=>`<p>${x}</p>`).join('');
const jobs=[
 {year:'2007',company:'GAMO a.s.',logo:'gamo',role:'IBM Lotus Notes developer, webdesigner',copy:'My early development work combined website design with frontend implementation. IBM Lotus Notes introduced me to business applications and the connections between visual interfaces, shared information and server-side systems.',projects:['BBSK Portal','IRRR','SLEK','KVLSR','CRSZ','Kremnica Gags']},
 {year:'2010',company:'SCR',logo:'scr',role:'Front-end developer, PHP developer',copy:'Agency work expanded my experience in frontend development and PHP. I helped turn visual concepts into websites for a range of organisations, working across presentation, implementation and the practical details of delivery.',projects:['TA3','Radio Express','SWAN','Energio','Gas Familia','Flatbook'],extra:'Additional brand work included O2, Sony, Pelikan, Corgoň, Zlatý Bažant and Heineken.'},
 {year:'2012',company:'Kremsa Digital',logo:'kremsa',role:'MEAN stack developer, Angular & Front-end developer, PHP & Wordpress developer',copy:'At Kremsa Digital, my work grew towards complete applications. Angular and the MEAN stack joined earlier PHP and WordPress experience, allowing me to connect frontend interfaces with the services and data behind them.',projects:['Pioneer Projects CRM','SMBee'],extra:'Pioneer Projects CRM: MongoDB, Node.js, Angular and ExpressJS. SMBee: Node.js, MySQL, InfluxDB, Angular, Google Firebase and ExpressJS. Other projects involved Legrand, Slovakia Chips, Karloff, Rajo, FONA, Amoeba, HB Reavis and Atheer Labs.'},
 {year:'2018',company:'Bethereum',logo:'bethereum',role:'Angular & Front-end developer',copy:'This role focused on Angular and frontend development, bringing my experience with interactive interfaces to a dedicated product team. The work continued the shift from individual websites to richer application experiences.'},
 {year:'2020',company:'VUB Bank',logo:'vub',role:'Angular & Front-end developer',copy:'At VUB Bank, part of Intesa Sanpaolo Group, my current work focuses on Angular applications and the automation of banking processes. It brings together frontend development and an understanding of complex operational workflows.',current:true}
];
const knownLinks={'KVLSR':'https://www.kvlsr.sk/','CRSZ':'https://www.crsz.sk/','Kremnica Gags':'https://gagy.eu/','Gas Familia':'https://www.gasfamilia.com/','Flatbook':'https://flatbook.sk/'};
Pages.cv=()=>`<article class="panel cv-panel"><h1>Curriculum Vitae</h1><div class="cv-intro">${paragraphs([
'My development career spans 19 years, with a continuing focus on frontend work and JavaScript applications.',
'My experience reaches beyond a single part of the stack. Working with visual design, interfaces and backend development has shaped the way I approach software. It helps me understand the priorities of designers and engineers and connect their work into one coherent product. Over time, my focus has moved from graphic and web development towards complex Angular applications and full-stack systems.',
'The timeline below follows that progression, from early agency and web projects to product development and the automation of banking workflows.'
])}</div><div class="timeline">${jobs.map((j,i)=>`<section class="job"><div class="job-year"><img src="assets/images/logos/cv-${j.logo}.webp" alt="${j.company}"><span>${j.year}</span></div><div class="job-body"><h2>${j.company}</h2>${j.current?'<div class="current">Intesa Sanpaolo Group · Current position</div>':''}<h3>${j.role}</h3><p>${j.copy}</p>${j.projects?`<button class="pixel-button project-toggle" aria-expanded="false" data-expand="${i}">Show projects</button><div class="selected-projects" id="job-projects-${i}" hidden><h3>Selected projects</h3>${j.projects.map(n=>`<div class="selected-project"><h4>${n}</h4>${knownLinks[n]?`<a class="pixel-button blue" href="${knownLinks[n]}" target="_blank" rel="noopener">Visit</a>`:''}</div>`).join('')}${j.extra?`<p>${j.extra}</p>`:''}</div>`:''}</div></section>`).join('')}</div><p class="cv-end">Let's connect on <a href="https://www.linkedin.com/in/peteroravec" target="_blank" rel="noopener">LinkedIn</a> to discuss development and future projects.</p>${up}</article>`;
const projects=[
 {name:'eUTxO.org',subtitle:'Visual Blockchain Explorer for Cardano',image:'portfolio-eutxo.webp',url:'https://eutxo.org/',copy:'A visual way to explore Cardano blocks and the UTXO structure. Instead of presenting the blockchain only as rows of data, this project gives its connections a visual form, bringing backend information into an interactive browser experience.',tags:['Serverless Node.js','Google Firestore DB','BlockFrost API','PhaserJS','Tailwind CSS']},
 {name:'Angular.sk',subtitle:'Free online course for Angular 2+',image:'portfolio-angularsk.webp',url:'https://angular.sk/',copy:'A free video course that introduces Angular 2+ to beginners, sharing practical development knowledge through an accessible learning resource.',tags:['Angular','Javascript']},
 {name:'Peter Oravec portfolio v1',subtitle:'100% human-coded, no AI',image:'peteroravec-v1.webp',url:'https://old.peteroravec.com/',copy:'An earlier, hand-written version of this pixel portfolio. It combines Angular interfaces, a PhaserJS game world and a map created with Tiled, using a playful environment to present professional work. The project explores how a personal website can invite visitors to interact and discover.',tags:['Angular','PhaserJS','Tiled']}
];
Pages.projects=()=>`<div class="project-page"><article class="panel"><h1>Projects</h1><p>These personal projects explore different sides of my work: visual tools, teaching and interactive websites. For the broader professional story and selected client work, visit the Resume (CV) section.</p></article>${projects.map(p=>`<article class="panel project-card"><img src="assets/images/portfolio/${p.image}" alt="${p.name} project preview"><h2>${p.name}</h2><h3>${p.subtitle}</h3><p>${p.copy}</p><div class="tech-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><a class="pixel-button blue visit" href="${p.url}" target="_blank" rel="noopener">Visit</a></article>`).join('')}<div class="panel">${up}</div></div>`;
const techs=[
 ['Angular','angular','TypeScript JavaScript framework for building SPA applications',['Angular is central to my work on complex single-page applications. I use it to organise rich interfaces and connect the parts of a product into a consistent experience, from structure and data to animation and interaction.','My professional background includes Angular projects across product development and banking workflows.']],
 ['Node.js','nodejs','JavaScript beyond the browser',['Node.js connects my frontend experience with service-side logic. It makes it possible to work with one language across interfaces, APIs and the systems that support them.','My projects use server-side JavaScript alongside different data stores and external services. This experience helps me understand how an interface depends on the shape, reliability and behaviour of its backend.']],
 ['Express.JS','expressjs','A practical foundation for backend services',['Express provides a way to organise Node.js applications and APIs. It has been part of my MEAN stack work, connecting application logic, data and browser interfaces.']],
 ['Javascript','javascript','The language that connects my work',['JavaScript is the common thread through my development experience. It supports the interfaces people interact with, the services behind those interfaces and visual work in Canvas.','Moving between these uses keeps the work interesting. A language that handles application logic can also bring a scene to life, making technical ideas visible and interactive.']]
];
Pages.technologies=()=>`<article class="panel technologies-panel"><h1>Technologies</h1><p class="tech-intro">My experience spans frontend development, visual design and backend systems. These are the technologies I use to bring those disciplines together and turn ideas into applications.</p><div class="technology-list">${techs.map(([name,key,sub,paras])=>`<section class="technology tech-${key}"><img src="assets/images/logos/dev-${key}.webp" alt="${name}"><div><h2>${name.toUpperCase()}</h2><h3>${sub}</h3>${paragraphs(paras)}</div></section>`).join('')}</div><h2 class="other-title">Other technologies and experience</h2><ul class="other-tech">${['Automation via Puppeteer','Automated tests via Midnight, Playwright','MongoDB','HTML / CSS','Phaser.js - 2D canvas / WebGL game engine','Photoshop','MySQL','Google Firestore','Mockflow - wireframes'].map(t=>`<li>${t}</li>`).join('')}</ul>${up}</article>`;
window.Memos=[
 {title:'100% Vibe coding',x:294,y:222,paras:['This experiment explores how AI can accelerate the making of a complex digital experience. Generating code is one part of the process; bringing that code together into a coherent product still calls for human judgement.','Fast output is useful when the direction is clear.','The developer supplies context, chooses the approach and decides how the pieces should fit. Those decisions give the generated work a purpose and a consistent structure.','Context matters throughout the process. Clear tasks and an understanding of the existing work help keep each new contribution connected to the whole.','Generated code needs review. Integration, testing and careful adjustment remain essential, especially for details that are easy to miss in a quick first pass.','AI can extend what a developer is able to create. Its value comes from the combination of speed and human responsibility: someone must still decide, verify and bring the result together.']},
 {title:'Automatic testing',x:26,y:361,paras:['Automated checks make delivery more repeatable. Browser and API tests help verify that the important parts of an application continue to work as it changes.','My testing toolkit includes Midnight, Playwright, Puppeteer, Mocha and Chai.','Tests are useful feedback: they support development by checking behaviour and making problems easier to notice.']},
 {title:'From Node.js logic to visual art in Canvas',x:327,y:291,paras:['JavaScript can move from server-side logic in Node.js to interfaces and visual expression in Canvas. These are different kinds of work, but they share a language and a way to turn ideas into behaviour.','That connection is part of what makes development interesting to me. Data and logic can become something people can see, navigate and interact with, linking technical work to a visual experience.']},
 {title:'Technologies I buried',x:351,y:38,paras:['Earlier technologies are part of the journey, even when they are no longer the focus of everyday work. Each one leaves behind useful experience in solving problems and understanding software.','My current focus is JavaScript and its ecosystem. The older chapters help explain how I arrived here.']},
 {title:'AI: Competitor or colleague?',x:302,y:112,paras:['AI can produce code quickly, but speed alone does not decide whether that code is right for a project. People still choose the goals and make the trade-offs.','I see it as a collaborator whose output needs context, review and a developer’s judgement.']},
 {title:"I'm not a game developer",x:84,y:33,paras:['The pixel world is a creative way to present my work and invite exploration. It reflects an interest in visual interaction.','My main professional focus remains software development and long-term application projects.']}
];
Pages.memo=()=>`<article class="panel memo-panel"><h1>#memos</h1><div class="memo-grid">${Memos.map((m,i)=>`<button class="memo-tile" data-memo="${i}" aria-label="${m.title}"><img src="assets/images/cards/card${i+1}_base.webp" alt="${m.title}"></button>`).join('')}</div></article>`;
Pages.card=i=>`<article class="panel card-panel"><div class="card-visual"><button class="holo-card" data-holo="${i+1}" aria-label="Activate card effect" style="--pattern:url('assets/images/cards/card${i+1}_${i===3?'foil':'pattern'}.webp')"><img src="assets/images/cards/card${i+1}_base.webp" alt="${Memos[i].title}"><span class="holo-shine"></span><span class="holo-sparkles"></span><img class="pointer-hint" src="assets/images/ui/pointer-hand.webp" alt="Touch the card"></button><nav class="card-navigation" aria-label="Memo navigation">${i>0?`<button data-memo="${i-1}" aria-label="Previous memo">❮</button>`:''}<button data-go="memo" aria-label="Memo menu">☰</button>${i<Memos.length-1?`<button data-memo="${i+1}" aria-label="Next memo">❯</button>`:''}</nav></div><div class="card-copy"><h1>${Memos[i].title}</h1>${paragraphs(Memos[i].paras)}</div></article>`;
Pages.contact=()=>`<article class="panel contact-panel"><h1>Contact</h1><p class="contact-intro">Find me online or get in touch<br>using the details below.</p><a class="contact-method" href="https://www.linkedin.com/in/peteroravec" target="_blank" rel="noopener">${linkIcon}<span><strong>LinkedIn</strong><span>linkedin.com/in/peteroravec</span></span></a><a class="contact-method" href="mailto:p.oravec@gmail.com"><span class="mail-icon" aria-hidden="true">M</span><span><strong>Email</strong><span>p.oravec@gmail.com</span></span></a></article>`;
window.Hood=[
 ['Architecture',[
'The reference portfolio brings two kinds of interface together: Angular handles the content and menus, while Phaser renders the pixel city. The visual world and the readable content remain separate layers, so each can use the tools that suit its role.',
'This reconstruction follows the same division of responsibilities with an independently written Canvas renderer and ordinary HTML content. The interface controls the active destination, while the scene manages the camera, moving sprites and transition effects.',
'The two layers share a small set of actions: move, visit a destination, open a panel and return to the city. Images and fonts are included locally, allowing the same experience to run as an offline folder or a hosted website.'
 ]],
 ['Phaser.js',[
'The original portfolio describes Phaser as the engine behind its interactive world. A game framework can organise scenes, cameras, sprite animation and the rendering of a large collection of objects.',
'Game scenes and web content have different needs. Keeping long text in HTML makes it naturally readable and scrollable, while a canvas can draw moving characters and environmental effects without creating a separate page element for every tile.',
'This study recreates those visible behaviours with a small independent Canvas implementation. It does not include the original Phaser code. Learn more about the framework at <a href="https://phaser.io/" target="_blank" rel="noopener">Phaser.js 3</a>.'
 ]],
 ['Chunk System',[
'A large map contains more detail than any single screen can show. The reference description explains how dividing the world into chunks helps control the amount of work needed as the camera moves.',
'The useful principle is to focus effort on the visible area and the region around it. Distant objects can remain outside the current rendering work, while nearby objects stay ready as the player approaches.',
'For this reconstruction, the background is rebuilt from the supplied image material. Moving objects are drawn only when their region is near the camera. The original map data and chunk implementation are not part of the input.'
 ],'debug1.webp'],
 ['NPC System',[
'Characters and vehicles make the city feel occupied even when the player is standing still. Their motion is separate from navigation and from the content panels above the scene.',
'The reference material describes NPC movement and routes as part of the world simulation. In this reconstruction, characters follow simple local paths, traffic follows roads and ducks stay near water. Their animation phases vary so they do not all move in unison.',
'These are independent approximations of the observed behaviour. The supplied package does not contain the original pathfinding, collision map or complete movement routes.'
 ],'debug2.webp'],
 ['Tiled Editor',[
'The reference portfolio uses Tiled to arrange its pixel world. A tile editor makes it possible to combine reusable ground, buildings and objects into a larger connected map.',
'The reconstruction input includes the original tile artwork and a small complete-map image, together with reference screenshots. It does not include the original map logic or the editor’s machine-readable layout.',
'This version reconstructs the city from those allowed visual inputs. The result preserves the major districts and destinations, while the exact placement of some tiles and obstacles remains an approximation.'
 ],'tiled1.webp'],
 ['Optimization',[
'An animated city should remain responsive while the visitor walks, opens a map or reads a panel. The reference description highlights viewport culling, chunks and background computation as ways to keep the work under control.',
'This version draws one scene per animation frame, reuses loaded image assets and checks whether moving objects are near the visible area. The content layer scrolls independently, so reading does not move the game camera.',
'Offline operation is also part of the delivery. The scene, interface images, project pictures and fonts load from the local package, without needing the reference website to remain available.'
 ]]
];
Pages.hood=()=>`<article class="panel hood-panel"><header><h1>Under the Hood</h1><p>How does this portfolio work?</p></header><div class="hood-layout"><nav aria-label="Technical topics">${Hood.map(([name],i)=>`<button data-hood="${i}" class="${i===0?'selected':''}" aria-selected="${i===0}">${name}</button>`).join('')}</nav><section class="hood-content" id="hood-content">${hoodContent(0)}</section></div></article>`;
function hoodContent(i){return `<h2>${Hood[i][0]}</h2>${paragraphs(Hood[i][1])}${Hood[i][2]?`<img src="assets/images/under-the-hood/${Hood[i][2]}" alt="${Hood[i][0]} reference illustration">`:''}`}
window.Locations=[{id:'about',label:'About me',x:166,y:135},{id:'cv',label:'Resume (CV)',x:82,y:304},{id:'projects',label:'Projects',x:212,y:219},{id:'technologies',label:'Technologies',x:63,y:174},{id:'contact',label:'Contact',x:303,y:365},...Memos.map((m,i)=>({id:'card'+i,label:'Memo #'+(i+1),x:m.x,y:m.y,memo:i}))];
Pages.map=()=>`<div class="crt"><div class="crt-screen"><img class="world-map" src="assets/maps/big-map.webp" alt="Map of the pixel city"><div class="map-legend"><span><i class="info"></i>Info</span><span><i class="memo"></i>Memo</span><span><i class="visited"></i>Visited</span></div><div class="map-locations">${Locations.map(l=>`<button class="map-location ${l.memo!==undefined?'memo':'info'} ${window.visited?.has(l.id)?'visited':''}" style="left:${l.x/4}%;top:${l.y/4}%" ${l.memo!==undefined?`data-memo="${l.memo}"`:`data-go="${l.id}"`} aria-label="Visit ${l.label}"><i></i><span>${l.label}</span></button>`).join('')}</div><img class="map-player" id="large-player" src="assets/images/peter-oravec.gif" alt="Your position" style="left:${City.player.x/4}%;top:${City.player.y/4}%"></div><img class="crt-frame" src="assets/images/ui/monitor.webp" alt="CRT monitor"></div>`;
